name: CI
on:
  push:
    branches: ['**']
    tags-ignore: ['**']
  pull_request:
  schedule:
    - cron: '0 2 * * *'
jobs:
  test:
    strategy:
      matrix:
        fail-fast: false
        os: [ubuntu]
        ruby: [2.5, 2.6, 2.7, jruby, truffleruby]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '2.x'
      - name: Install Packages
        run: |
          sudo apt-get install -qq haveged
          sudo apt-get install -qq gconf-service
          sudo apt-get install -qq libasound2
          sudo apt-get install -qq libatk1.0-0
          sudo apt-get install -qq libc6
          sudo apt-get install -qq libcairo2
          sudo apt-get install -qq libcups2
          sudo apt-get install -qq libdbus-1-3
          sudo apt-get install -qq libexpat1
          sudo apt-get install -qq libfontconfig1
          sudo apt-get install -qq libgcc1
          sudo apt-get install -qq libgconf-2-4
          sudo apt-get install -qq libgdk-pixbuf2.0-0
          sudo apt-get install -qq libglib2.0-0
          sudo apt-get install -qq libgtk-3-0
          sudo apt-get install -qq libnspr4
          sudo apt-get install -qq libpango-1.0-0
          sudo apt-get install -qq libpangocairo-1.0-0
          sudo apt-get install -qq libstdc++6
          sudo apt-get install -qq libx11-6
          sudo apt-get install -qq libx11-xcb1
          sudo apt-get install -qq libxcb1
          sudo apt-get install -qq libxcomposite1
          sudo apt-get install -qq libxcursor1
          sudo apt-get install -qq libxdamage1
          sudo apt-get install -qq libxext6
          sudo apt-get install -qq libxfixes3
          sudo apt-get install -qq libxi6
          sudo apt-get install -qq libxrandr2
          sudo apt-get install -qq libxrender1
          sudo apt-get install -qq libxss1
          sudo apt-get install -qq libxtst6
          sudo apt-get install -qq ca-certificates
          sudo apt-get install -qq fonts-liberation
          sudo apt-get install -qq libappindicator1
          sudo apt-get install -qq libnss3
          sudo apt-get install -qq lsb-release
          sudo apt-get install -qq xdg-utils
          sudo apt-get install -qq curl
          sudo apt-get install -qq python-gtk2 python-cairo
          sudo apt-get install -qq ttf-dejavu
      - name: Install Ruby dependencies
        run: bundle install --path vendor/bundle --jobs=3 --retry=3
      - name: Install Graphviz
        run: sudo apt-get install -qq graphviz
      - name: Install Lilypond
        run: sudo apt-get install -qq lilypond
      - name: Install BPNM-JS
        run: npm install -g bpmn-js-cmd
      - name: Install Mermaid
        run: npm install -g @mermaid-js/mermaid-cli
      - name: Install NomNoml
        run: npm install -g nomnoml
      - name: Install StateMachineCat
        run: npm install -g state-machine-cat
      - name: Install Vega
        run: |
          npm install -g vega-cli
          npm install -g install-peerdeps
          install-peerdeps -g vega-lite
      - name: Install Wavedrom
        run: npm install -g wavedrom-cli
      - name: Install Gnuplot
        run: sudo apt-get install -qq gnuplot
      - name: Install UMLet
        run: |
          curl -s -O http://www.umlet.com/umlet_14_2/umlet-standalone-14.2.zip
          unzip -qq umlet-standalone-14.2.zip
          cp Umlet/umlet.sh Umlet/umlet
          chmod +x Umlet/umlet
          export PATH=$PATH:$PWD/Umlet/
      - name: Install MSCgen
        run: sudo apt-get install -qq mscgen
      - name: Install Python-based Tools
        run: |
          python -m pip install --upgrade pip
          pip install --user -r pip-requirements.txt -c pip-constraints.txt
          export BLOCKDIAG_FONTPATH=/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf
      - name: Run tests
        run: bundle exec ruby -w $(bundle exec ruby -e 'print File.join Gem.bindir, %q(rake)') spec